services:
  devsnap-db:
    container_name: devsnap-db
    image: postgres
    environment:
      POSTGRES_USER: devsnap_user
      POSTGRES_PASSWORD: devsnap_password
      POSTGRES_DB: devsnap_db
      PGDATA: /data/lib/postgresql/data
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
